name: Iron RHEL Binary Build
on:
  workflow_dispatch:
  push:
    branches:
      - iron
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  iron_rhel_binary:
    name: Iron RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: iron
    container: ghcr.io/ros-controls/ros:iron-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_controllers
<<<<<<< HEAD
      - run: |
=======
          ref: ${{ github.event_name == 'schedule' && 'iron' || '' }}
      - name: Install dependencies
        run: |
>>>>>>> 737a45b (Use correct ref for scheduled workflows (#1013))
          rosdep update
          rosdep install -iy --from-path src/ros2_controllers
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
