name: Rolling RHEL Binary Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'


jobs:
  rolling_rhel_binary:
    name: Rolling RHEL binary build
    runs-on: ubuntu-latest
    env:
      ROS_DISTRO: rolling
    container: ghcr.io/ros-controls/ros:rolling-rhel
    steps:
      - uses: actions/checkout@v4
        with:
          path: src/ros2_controllers
<<<<<<< HEAD
      - run: |
=======
          # default behavior is correct on master branch
          # ref: ${{ github.event_name == 'schedule' && 'master' || '' }}
      - name: Install dependencies
        run: |
>>>>>>> 737a45b (Use correct ref for scheduled workflows (#1013))
          rosdep update
          rosdep install -iy --from-path src/ros2_controllers
          source /opt/ros/${{ env.ROS_DISTRO }}/setup.bash
          colcon build
          colcon test
